name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build_job:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['19']
        os: [windows-latest]
  
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    
    - name: Nextjs caching
    - uses: actions/cache@v3
    - with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
          
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
  
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
        
    
